use crossterm::style::Color;
use serde::Deserialize;
use std::collections::HashMap;
use std::fs;

#[derive(Deserialize)]
struct ColorsJson {
    colors: HashMap<String, String>,
}

pub struct Palette {
    /// Vibrant accent colors (color1..color6 + color9..color14 from the
    /// refract palette). One is picked per track via `pick_accent`.
    pub accents: Vec<Color>,
    pub dim: Color,
}

impl Default for Palette {
    fn default() -> Self {
        Self {
            accents: vec![Color::Cyan],
            dim: Color::DarkGrey,
        }
    }
}

/// Reuses the palette generated by `refract` (../refract) so the lyric view
/// matches the current wallpaper-derived theme.
pub fn load() -> Palette {
    let default = Palette::default();
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    let path = format!("{home}/.cache/refract/colors.json");

    let Ok(content) = fs::read_to_string(path) else { return default };
    let Ok(parsed) = serde_json::from_str::<ColorsJson>(&content) else { return default };

    // Skip color0/color7/color8/color15 — those are background/foreground/grey
    // and would either clash with the terminal bg or look washed out as the
    // active lyric color.
    let vibrant_keys = [
        "color1", "color2", "color3", "color4", "color5", "color6",
        "color9", "color10", "color11", "color12", "color13", "color14",
    ];

    let accents: Vec<Color> = vibrant_keys
        .iter()
        .filter_map(|k| parsed.colors.get(*k).and_then(|h| hex_to_color(h)))
        .collect();

    let accents = if accents.is_empty() { default.accents } else { accents };
    let dim = parsed.colors.get("color8").and_then(|h| hex_to_color(h)).unwrap_or(default.dim);

    Palette { accents, dim }
}

/// Deterministically picks an accent color for the given track. Same song →
/// same color (no flicker on repeat), different songs cycle through the full
/// vibrant set.
pub fn pick_accent(palette: &Palette, title: &str, artist: &str) -> Color {
    if palette.accents.is_empty() {
        return Color::Cyan;
    }
    let mut hash: u64 = 1469598103934665603; // FNV-1a offset
    for b in title.bytes().chain(artist.bytes()) {
        hash ^= b as u64;
        hash = hash.wrapping_mul(1099511628211);
    }
    palette.accents[(hash as usize) % palette.accents.len()]
}

fn hex_to_color(hex: &str) -> Option<Color> {
    let hex = hex.trim_start_matches('#');
    if hex.len() != 6 {
        return None;
    }
    let r = u8::from_str_radix(&hex[0..2], 16).ok()?;
    let g = u8::from_str_radix(&hex[2..4], 16).ok()?;
    let b = u8::from_str_radix(&hex[4..6], 16).ok()?;
    Some(Color::Rgb { r, g, b })
}
